### ISSUE TITLE
Codes for evaluating Diversity and Novelty Metrics

### ISSUE THREAD

**Issue by hhhhh789** [bytedance/dplm#7]
Despite of pLDDT and pTM, I want other metrics in the paper difficult to follow. It would be appreciated that you could provide details calculating pdb-TM and innerTM, as well as settings of sampling(Are there any different from pLDDT 500steps & 40 candidates).
I've tried to calculate inner-TM myself(mean of 1560 pairs for 40 candidates) but collected much lower value than reported in the paper.

**Comment by wxy-nlp** [comment]
Hello @hhhhh789, there must be something weird because I didn't get notified of your issue so sorry for the late reply. I have updated the script of calculating the TMscore, you can calculate the TMscore for diversity like this:
```
query_dir=./generation-results/dplm_650m/esmfold_pdb
reference_dir=./generation-results/dplm_650m/esmfold_pdb
# or the path of all pdb files to calculate the novelty

python cal_tmscore.py --query_dir ${query_dir} --ref_dir ${ref_dir} --cal_type diversity
```

After this you can see the `diversity` folder in the `./generation-results/dplm_650m/` path, and you can plot the diversity in the `analysis/uncond_analysis.ipynb`.
